name: Python CI

on:
  [push, pull_request]:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@ma
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: run src/tests.py
